---

# C4. Exercițiu individual: construirea unui mini-prompt de adnotare

În acest exercițiu construiești un prompt mic de adnotare pentru comentarii politice.
- Intelegem cum se construiește un prompt: rol, variabile, definiții, reguli și format JSON.
- Alegemdouă axe proprii sau două axe din curs și vei testa promptul pe 5 comentarii.

## Pasul 0 . Configurare

In [18]:
import os, json, re, random
from pathlib import Path
from openai import OpenAI
from dotenv import load_dotenv
# caută .env urcând din folderul curent

ROOT = Path.cwd()
while not (ROOT / ".env").exists() and ROOT.parent != ROOT:
    ROOT = ROOT.parent
load_dotenv(ROOT / ".env")

# DeepSeek
deepseek_client = OpenAI(
    api_key=os.getenv("DEEPSEEK_API_KEY"),
    base_url="https://api.deepseek.com"
)
DEEPSEEK_MODEL = "deepseek-chat"
# Gemini prin OpenAI-compatible API
gemini_client = OpenAI(
    api_key=os.getenv("GEMINI_API_KEY"),
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)

GEMINI_MODEL = "gemini-2.5-flash-lite"
# alegem modelul pentru demo

USE_GEMINI = False
client_now = gemini_client if USE_GEMINI else deepseek_client
model_now = GEMINI_MODEL if USE_GEMINI else DEEPSEEK_MODEL
print("Root project:", ROOT)
print("DeepSeek key:", os.getenv("DEEPSEEK_API_KEY") is not None)
print("Gemini key:", os.getenv("GEMINI_API_KEY") is not None)
print("Model folosit:", model_now)
print("OK")

Root project: c:\Users\User\Documents\GitHub\echochamber-project-team-1
DeepSeek key: True
Gemini key: True
Model folosit: deepseek-chat
OK

## Corpus

In [19]:
import pandas as pd
from pathlib import Path

ROOT = Path(r"c:\Users\User\Documents\GitHub\echochamber-project-team-1")

corpus_file = ROOT / "data" / "cleaned" / "corpus_youtube_sample.jsonl"

print(corpus_file.exists())
print(corpus_file)

corpus = pd.read_json(corpus_file, lines=True)

print(len(corpus), "comentarii")
print("Câmpuri:", list(corpus.columns))

for _, c in corpus.sample(3).iterrows():
    print(f"[{c['source_channel'][:30]}] {c['text'][:80]}")

True
c:\Users\User\Documents\GitHub\echochamber-project-team-1\data\cleaned\corpus_youtube_sample.jsonl
420 comentarii
Câmpuri: ['id', 'source_channel', 'video_title', 'text']
[RecorderRomania] Vă urmăresc pentru că sunteți cea mai bună și profesionistă sursă . Dar aici ați
[b1tvchannel] Despre Georgescu, nu cred că habaucii, analfabeții care, de fiecare dată când es
[happyfishteleviziune] Ce s-a intamplat din anul 598- 1798 ( Evul mediu intunecat ), acelasi lucru se v

### Pasul 1 Alege două axe

Alege două axe pe care vrei să le codezi.
Poți folosi axe din curs:
- institutional
- legitimare
- epistemic
- geopolitic
- mobilizare
Sau poți propune axe proprii:
- media_distrust
- elite_blame
- religious_frame
- fear
- irony
- people_vs_elite
- anti_corruption
- national_identity
Condiție: fiecare axă trebuie să aibă valori clare.
Pentru acest exercițiu folosim o scală simplă:
0 = absent
1 = prezent

In [20]:
# modifica dupa preferinte

AXA_1 = "epistemic"
AXA_2 = "geopolitic"

## Pasul 2 — Definește axele
Scrie mai jos, în propriile cuvinte, ce înseamnă fiecare axă.
Exemplu:
media_distrust = comentariul exprimă neîncredere în presă, jurnaliști, televiziuni sau media mainstream.
religious_frame = comentariul folosește limbaj religios pentru a interpreta politica.

In [21]:
AXA_1_DEFINITION = """
epistemic măsoară dacă textul exprimă scepticism sau neîncredere în cunoștințele științifice.
0 = absent
1 = prezent
2 = dominant
"""
AXA_2_DEFINITION = """
geopolitic măsoară dacă textul abordează aspecte geografice sau politice.
0 = absent
1 = prezent
2 = dominant
"""

## Pasul 3 — Construiește mini-promptul
Promptul trebuie să conțină:
1. rolul modelului;
2. sarcina;
3. definițiile celor două axe;
4. regulile de codare;
5. formatul JSON.
Important:
- nu cere modelului să identifice direct „bula”;
- nu cere text liber;
- returnează doar JSON valid.

In [22]:
MINI_PROMPT = f"""
Ești un adnotator uman care analizează comentarii de pe YouTube pentru un proiect de cercetare. Fiecare comentariu trebuie adnotat pe baza a două axe tematice, alături de identificarea țintei politice, poziției față de aceasta și tonului general al textului.
SARCINĂ:
Adnotează comentariul folosind două axe:
1. {AXA_1}
2. {AXA_2}
CÂMPURI:
target = ținta politică principală din comentariu
stance = poziția față de target: pro / anti / neutru / ambiguu / none
tone = modul dominant de formulare: acuzator / ironic / mobilizator / defensiv / afectiv / neutru
{AXA_1} = 0 / 1 / 2
{AXA_2} = 0 / 1 / 2
DEFINIȚII:
{AXA_1_DEFINITION}
{AXA_2_DEFINITION}
REGULI:
1. Codează doar ce apare în comentariu, titlu sau canal.
2. Nu inventa informații externe.
3. Dacă nu există target politic, folosește target="none" și stance="none".
4. Dacă textul este ironic, codează sensul intenționat, nu sensul literal.
5. Pentru axe: 0 = absent, 1 = prezent, 2 = dominant.
6. Nu atribui direct o bulă discursivă.
7. Returnează doar JSON valid.
FORMAT OUTPUT:
{{
  "target": "",
  "stance": "",
  "tone": "",
  "{AXA_1}": 0,
  "{AXA_2}": 0
}}
"""
print(MINI_PROMPT)

Ești un adnotator uman care analizează comentarii de pe YouTube pentru un proiect de cercetare. Fiecare comentariu trebuie adnotat pe baza a două axe tematice, alături de identificarea țintei politice, poziției față de aceasta și tonului general al textului.
SARCINĂ:
Adnotează comentariul folosind două axe:
1. epistemic
2. geopolitic
CÂMPURI:
target = ținta politică principală din comentariu
stance = poziția față de target: pro / anti / neutru / ambiguu / none
tone = modul dominant de formulare: acuzator / ironic / mobilizator / defensiv / afectiv / neutru
epistemic = 0 / 1 / 2
geopolitic = 0 / 1 / 2
DEFINIȚII:

epistemic măsoară dacă textul exprimă scepticism sau neîncredere în cunoștințele științifice.
0 = absent
1 = prezent
2 = dominant


geopolitic măsoară dacă textul abordează aspecte geografice sau politice.
0 = absent
1 = prezent
2 = dominant

REGULI:
1. Codează doar ce apare în comentariu, titlu sau canal.
2. Nu inventa informații externe.
3. Dacă nu există target politic, folosește target="none" și stance="none".
4. Dacă textul este ironic, codează sensul intenționat, nu sensul literal.
5. Pentru axe: 0 = absent, 1 = prezent, 2 = dominant.
6. Nu atribui direct o bulă discursivă.
7. Returnează doar JSON valid.
FORMAT OUTPUT:
{
  "target": "",
  "stance": "",
  "tone": "",
  "epistemic": 0,
  "geopolitic": 0
}

## Pasul 4 — Alege 5 comentarii de test
Folosim un eșantion mic. Nu adnotăm tot corpusul.
Schimbă `random_state` ca să primești alte comentarii.

In [23]:
TESTS = corpus.sample(20)
TESTS[["id", "source_channel", "video_title", "text"]].head()

,id,source_channel,video_title,text
386,yt_iH8jB4NlV9Y_Ugz2SGyAmn4oGKy_iql4AaABAg,georgesimionoficial,Episodul 2: Cum ne-au furat alegerile - Turism...,Violul de la tabara AUR nu este o minciuna! Ex...
332,yt_TpUDm4ay-B8_Ugwazimbs6v6VBK4OTB4AaABAg,RecorderRomania,DOCUMENTAR RECORDER. Justiție capturată,Este dacă este să respecte regulile și Adevăru...
77,yt_gv9JYLtI6bw_UgwjDm2Enix1WUdVmwZ4AaABAg,spotmediaro,Ce știu cetățenii despre poliția locală?,Trebuie desființarea miliție locala și jandarm...
0,yt_Vekhmz5OPCc_UgzpXOYhxlT3Nqo6h7J4AaABAg,NicusorDanRO,🟢 LIVE Declarații de presă susținute la Palatu...,jigodia aia de Georgescu nu lua intrebari inca...
358,yt_CY3LNhAfypM_UgxQm1cxGQHXax-15-N4AaABAg,georgesimionoficial,"Sâmbra Oilor, datini și tradiții românești. Du...",SIMION A MULȚUMIT CASEI ALBE PENTRU ANULAREA V...

## Pasul 5 — Rulează promptul pe cele 5 comentarii
Pentru fiecare comentariu:
1. trimitem canalul, titlul video și textul;
2. modelul returnează JSON;
3. citim rezultatul și verificăm dacă are sens.

In [24]:
USE_GEMINI = False
client_now = gemini_client if USE_GEMINI else deepseek_client
model_now = GEMINI_MODEL if USE_GEMINI else DEEPSEEK_MODEL
print("Using:", model_now)

Using: deepseek-chat

In [25]:
def llm(system, user, max_tokens=700):
    response = client_now.chat.completions.create(
        model=model_now,
        temperature=0,
        max_tokens=max_tokens,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user}
        ]
    )
    return response.choices[0].message.content

In [27]:
results = []

for _, row in TESTS.iterrows():

    USER = f"""
CANAL:
{row.get("source_channel", "")}

TITLU VIDEO:
{row.get("video_title", "")}

COMENTARIU:
<<< {row["text"]} >>>
"""

    try:
        raw = llm(MINI_PROMPT, USER, max_tokens=300)

        print("=" * 80)
        print("ID:", row["id"])
        print()
        print("COMENTARIU:")
        print(row["text"])
        print()
        print("OUTPUT MODEL:")
        print(raw)

        results.append({
            "id": row["id"],
            "text": row["text"],
            "model_output": raw
        })

    except Exception as e:
        print("EROARE la id:", row["id"])
        print(e)

================================================================================
ID: yt_iH8jB4NlV9Y_Ugz2SGyAmn4oGKy_iql4AaABAg

COMENTARIU:
Violul de la tabara AUR nu este o minciuna! Exista raport medico-legal care a demonstrat faptul ca fata a fost victima unui viol. Sa nu recunosti intamplarea si sa o numesti minciuna arata doar cat de interesat e gunoiul asta de siguranta femeilor

OUTPUT MODEL:
{
  "target": "AUR",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_TpUDm4ay-B8_Ugwazimbs6v6VBK4OTB4AaABAg

COMENTARIU:
Este dacă este să respecte regulile și Adevărul cinstit curat și fără diferente dintre cei dintre cetățeni și funcționari publici din România la nivelul national

OUTPUT MODEL:
{
  "target": "justiția din România",
  "stance": "pro",
  "tone": "mobilizator",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_gv9JYLtI6bw_UgwjDm2Enix1WUdVmwZ4AaABAg

COMENTARIU:
Trebuie desființarea miliție locala și jandarmeriei!Ceaușescu avea doar miliția comunista și era deajuns acum e plin de putori card sug din bugetul local și național

OUTPUT MODEL:
{
  "target": "poliția locală și jandarmeria",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_Vekhmz5OPCc_UgzpXOYhxlT3Nqo6h7J4AaABAg

COMENTARIU:
jigodia aia de Georgescu nu lua intrebari inca din campanie, cand NU AVEA PUTEREA ,cum zic americanii writings were on the wall'' scria clar pe perete ce va face avand puterea

OUTPUT MODEL:
{
  "target": "Călin Georgescu",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_CY3LNhAfypM_UgxQm1cxGQHXax-15-N4AaABAg

COMENTARIU:
SIMION A MULȚUMIT CASEI ALBE PENTRU ANULAREA VIZELOR SUA PENTRU ROMÂNI. Trădător împuțit

OUTPUT MODEL:
{
  "target": "George Simion",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_RU8h59PnVDM_Ugxw6Vquj0Br3S0VMGV4AaABAg

COMENTARIU:
Lepra aia care ia interval este non stop lângă el cine o fi 🙊🙈🙉🗣🗝

OUTPUT MODEL:
{
  "target": "none",
  "stance": "none",
  "tone": "afectiv",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_RRaqNih2zzg_Ugx1cbh818DYH3QLtjN4AaABAg

COMENTARIU:
Domnul cu Codiță i-e Globalist și i-e din Neamul lor....al Kazarilor

OUTPUT MODEL:
{
  "target": "Dan Diaconescu",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_sXqW2Cnw0DU_UgyFd08cuCXGNjBPclx4AaABAg

COMENTARIU:
Dictatorul Putin nu vrea pace, vrea capitularea necondiționată a ucrainenilor.

OUTPUT MODEL:
{
  "target": "Putin",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_e-Jkp8xRmsM_Ugz4kytsbjLpLpeoNPp4AaABAg

COMENTARIU:
Toate raspunsurile le gasim in Biblie . Foarte multe persoane apar in fata noastra ca “ profeti” atotstiutori ( si asta sta scris in Biblie) iar oamenii uita de Biblie de Dumnzeu . Mare pacat! Se insipra din Biblie si fac sa para ca ei au descoperit “ AMERICA “! Sa faca bani usor , caci oamenii sunt tare necajiti si bolnavi si chiar singuri .Stai pe genunchi dimineata , la pranz si seara de vorba. cu Creatorul tau , descara -ti sufletul , este gratuit! Domnul vin eoriunde si pricand te rogi si poti sa i mulyumesti ,da, chiar ca ai deschis ochii dimineata si poti merge ori pregati si manca micul dejun! Parerea mea ! 🫶🙏🏻

OUTPUT MODEL:
{
  "target": "none",
  "stance": "none",
  "tone": "afectiv",
  "epistemic": 1,
  "geopolitic": 0
}
================================================================================
ID: yt_xSxPpRcYQp0_UgybR4g38J4JGrEntdh4AaABAg

COMENTARIU:
Haideți sa lăudam pe Dumnezeu toți care ne încredem in EL și vom vedea răspunsul Sau

OUTPUT MODEL:
{
  "target": "none",
  "stance": "none",
  "tone": "afectiv",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_oRHUniqYnPs_UgyQ9bqRKVhbzsIdDBd4AaABAg

COMENTARIU:
Cat de legati la ochi tre sa fie unii... destramam europa, asta e... mna

OUTPUT MODEL:
{
  "target": "none",
  "stance": "none",
  "tone": "ironic",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_TpUDm4ay-B8_UgzplXTvhDsBpBquz4F4AaABAg

COMENTARIU:
Președintele nostru Mucușor o face pe prostul că este surprins de reportaj, ha-ha😂

OUTPUT MODEL:
{
  "target": "Mucușor",
  "stance": "anti",
  "tone": "ironic",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_XP-HViPnqMk_UgwJbMwYPXp5YwwLT4l4AaABAg

COMENTARIU:
Bună seara d-le Călin!Când viața ne apasă, ne dăm seama că adevărul și conștiința sunt singurele lucruri care ne țin în picioare. Eminescu ne amintește cine suntem și ce nu avem voie să pierdem: demnitatea și dreptatea în inimă, chiar și când ne doare.🌸🤗💛✨

OUTPUT MODEL:
{
  "target": "none",
  "stance": "none",
  "tone": "afectiv",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_yEuctxNb4O0_UgxPNjxaWPqCBL5WUAB4AaABAg

COMENTARIU:
Bun! S-a desfășurat aceasta întâlnire. S-a luat act despre această chestiune. Ce se întâmplă mai departe? Cum probeaza Nicușor că cele spuse sunt reale? Care sunt pașii de rezolvare a problemelor? Văd că mulți dintre ei au emotii, dar sunt câțiva extgrem de fermi, bine pregătiți și cu caractere extraordinare. Folosiți-va de ei în sensul bun, identificați problema, restabiliți legalitatea și echitatea în justiție!

OUTPUT MODEL:
{
  "target": "Nicușor Dan",
  "stance": "pro",
  "tone": "mobilizator",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_iH8jB4NlV9Y_UgxLlClp4R5tRu1clo54AaABAg

COMENTARIU:
pentru toți ăștia de ati votat cu legionaru ăsta, pe cine pula mea interesează videoclipurile astea? cine credeți voi ca o sa va asculte vreodată părerile voastre și faptul ca nu o sa puteți aduce niciodată vreun argument valid pentru care ăsta ar fi fost un președinte mai bun? nu vedeți ca pur și simplu va spala pe creier cu propoziții zise cu încetinitorul, fără argumente și doar zise așa ,,frumos" la modu crede-mă pe mine ca e mai bine așa

OUTPUT MODEL:
{
  "target": "georgesimion",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_zMTwPsQ26ZI_UgwSMJDiA_uqwHbI9Yh4AaABAg

COMENTARIU:
Parca mai zicea cineva că toți copii sunt genii.... Calin Georgescu .

OUTPUT MODEL:
{
  "target": "Calin Georgescu",
  "stance": "anti",
  "tone": "ironic",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_5AGO7BTxl_U_UgxvrsMlr7NiK2a7XBd4AaABAg

COMENTARIU:
Ce tot dati atâta importanță cum ca s-ar fi implicat Israelul sa reglementeze relatia cu SUA. Pe naiba ! Tot încercsti sa scoateti România basma curatá. Astea-s tertipuri naive si idioate. La ora actuala nu contam nimic. Cum sa-l admita Trump pe catastrofa de Nicusor când in 2020 a fost "luxat" venind catastrofa de Biden. La fel ca si dobitocul de Nicusor in 2024.

OUTPUT MODEL:
{
  "target": "Nicusor Dan",
  "stance": "anti",
  "tone": "acuzator",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_jxIZUCUPnAw_Ugwzh1OwH0iAS_vITHh4AaABAg

COMENTARIU:
Pai daca el a promis ucrainenilor, cum zici tu Robert, ?el executa ce i se ordona de cei care i.au pus

OUTPUT MODEL:
{
  "target": "none",
  "stance": "none",
  "tone": "neutru",
  "epistemic": 0,
  "geopolitic": 1
}
================================================================================
ID: yt_q6wy7cs5RuU_UgyZMtpEiT7-vCpWVVh4AaABAg

COMENTARIU:
Oameni pentru care lasi tot si iesi in strada sa ii sustii ❤ Va multumim pentru ceea ce faceti si pentru noi! 🙏

OUTPUT MODEL:
{
  "target": "judecătoarea Raluca Moroșanu",
  "stance": "pro",
  "tone": "afectiv",
  "epistemic": 0,
  "geopolitic": 0
}
================================================================================
ID: yt_XRhxwXmeOJE_UgyK8XmC0d25zyduV6R4AaABAg

COMENTARIU:
Ascultați și reascultati acest discurs.Este plin de mesaje …Poporul român se poate și trebuie să se elibereze singur.Așa cum au făcut strămoșii noștri,puterea este în noi înșine .Sa ne ridicăm,destinul e în mâinile noastre și sub protecția credinței noastre în Sfânta Treime ne vom recâștiga Libertatea..Totul spus din inimă și dintr-o suflare..Române,luptă ca țara ta să aibă un așa președinte ❤️.Sistemul nu va pleca de bunăvoie niciodată…

OUTPUT MODEL:
{
  "target": "Călin Georgescu",
  "stance": "pro",
  "tone": "mobilizator",
  "epistemic": 0,
  "geopolitic": 1
}

In [32]:
import json
import pandas as pd

typed_rows = []

for r in results:

    parsed = json.loads(r["model_output"])

    typed_rows.append({
        "text": r["text"],
        "target": parsed.get("target"),
        "stance": parsed.get("stance"),
        "tone": parsed.get("tone"),
        "epistemic": parsed.get("epistemic"),
        "geopolitic": parsed.get("geopolitic")
    })

typed = pd.DataFrame(typed_rows)

typed.head()

,text,target,stance,tone,epistemic,geopolitic
0,Violul de la tabara AUR nu este o minciuna! Ex...,AUR,anti,acuzator,0,0
1,Este dacă este să respecte regulile și Adevăru...,justiția din România,pro,mobilizator,0,1
2,Trebuie desființarea miliție locala și jandarm...,poliția locală și jandarmeria,anti,acuzator,0,1
3,jigodia aia de Georgescu nu lua intrebari inca...,Călin Georgescu,anti,acuzator,0,0
4,SIMION A MULȚUMIT CASEI ALBE PENTRU ANULAREA V...,George Simion,anti,acuzator,0,1

#  Minitipologie

In [33]:
def mini_typology(row):

    if row["epistemic"] >= 1 and row["geopolitic"] >= 1:
        return "comentariu politico-epistemic"

    elif row["epistemic"] >= 1:
        return "comentariu epistemic"

    elif row["geopolitic"] >= 1:
        return "comentariu geopolitic"

    else:
        return "comentariu fără axă dominantă"

In [34]:
typed["mini_typology"] = typed.apply(mini_typology, axis=1)

print(typed["mini_typology"])

0     comentariu fără axă dominantă
1             comentariu geopolitic
2             comentariu geopolitic
3     comentariu fără axă dominantă
4             comentariu geopolitic
5     comentariu fără axă dominantă
6             comentariu geopolitic
7             comentariu geopolitic
8              comentariu epistemic
9     comentariu fără axă dominantă
10            comentariu geopolitic
11    comentariu fără axă dominantă
12    comentariu fără axă dominantă
13    comentariu fără axă dominantă
14    comentariu fără axă dominantă
15    comentariu fără axă dominantă
16            comentariu geopolitic
17            comentariu geopolitic
18    comentariu fără axă dominantă
19            comentariu geopolitic
Name: mini_typology, dtype: str

## Interpretare mini-tipologie

Mini-tipologia construită pe baza axelor „epistemic” și „geopolitic” arată că majoritatea comentariilor din eșantion sunt de tip geopolitic sau fără axă dominantă. Comentariile geopolitice includ referințe la instituții, stat, politică sau contexte naționale și internaționale. Comentariile fără axă dominantă nu conțin elemente clare de scepticism epistemic sau referințe geopolitice. Axa epistemică apare mai rar în eșantion, ceea ce sugerează că majoritatea comentariilor analizate sunt mai degrabă orientate politic decât spre contestarea cunoașterii sau adevărului.

## Pasul 6 — Interpretare scurtă
Completează în notebook, în 3–5 rânduri:
- Ce două axe ai ales?
Am ales axele „epistemic” și „geopolitic”.
- De ce le-ai ales? 
Am ales aceste axe deoarece permit identificarea comentariilor care exprimă scepticism, afirmații considerate adevărate sau referințe politice și internaționale. Le-am ales pentru că sunt relevante în analiza discursului politic și a polarizării din comentariile YouTube.
- Modelul a returnat JSON corect?
 Modelul a returnat în general JSON corect și coerent, conform structurii cerute în prompt..
- Care a fost cea mai mare problemă?
 Cea mai mare problemă a fost limita de consum a API-ului Gemini, care a produs eroarea RateLimitError și a întrerupt procesarea completă a eșantionului. Ulterior am recurs la utilizarea deepseek.
- Ce ai schimba în prompt?
 Aș îmbunătăți promptul prin instrucțiuni mai stricte pentru returnarea exclusivă a obiectului JSON și prin exemple suplimentare pentru valorile axelor.